### ISSUE TITLE
pop-ups

### ISSUE THREAD

**Issue by burritojustice** [burritojustice/xyz_space_invader#10]
What would be useful information to show in a hover-based pop-up box? 

If a property were selected to show in the color property panel, perhaps we could show that value, along with well-known values like `name` or `label`).

Alternatively, we could provide a list of known property keys at the bottom the pop-up, and clicking on those would show their values when hovering over or clicking on a feature.

---

Blocking_Bicycle_Lane
Grey - Nissan Verda - 7PQG304
The report has been logged and will help the City collect data on double parking and bike lane violations to determine target areas and future enforcement efforts. Thank you.
---

caseid | closed | opened | source | status | address | updated | car_make | category | car_color | car_plate | media_url | neighborhood | _**request_type**_ | _**status notes**_ | police_district | _**request_details**_ | responsible agency | supervisor_district

**Comment by burritojustice** [comment]
the first part has been addressed in https://github.com/burritojustice/xyz_space_invader/pull/26

**Comment by burritojustice** [comment]
see also https://github.com/burritojustice/xyz_space_invader/issues/16

**Comment by bcamper** [comment]
Do we think there is more to do here, or are we OK with the new pop-up? (selected property value + click for more - though transition to showing all properties in the left sidebar when the pop-up closes is awkward as-is).

**Comment by burritojustice** [comment]
we could expand the pop-up to list all the properties, though that could get long (especially with the @ns object)

**Comment by bcamper** [comment]
Popups have been supercharged to show all properties, and support selecting a property and/or value to filter by.
