### ISSUE TITLE
allow selection of properties in nested objects

### ISSUE THREAD

**Issue by burritojustice** [burritojustice/xyz_space_invader#11]
It would be nice to be able to select a property of a nested object, like the value of an XYZ tag or the long route name.

https://min-max--xyz-space-invader.netlify.com/?space=hZiUfcqd&token=AOsE9k2EdCdT8lEX12PDZ38&basemap=refill-dark&buildings=0&points=0&lines=1&outlines=0&highlight=0&roads=1&water=0&colors=property&property=tags#12.943495566218068/37.7600/-122.4359

**Comment by bcamper** [comment]
Added in 1c853aea13a213f797332547d3a40bdfdd4ae26c
