### ISSUE TITLE
save screenshot to desktop

### ISSUE THREAD

**Issue by burritojustice** [burritojustice/xyz_space_invader#17]
Press `s` to save a tangram screenshot to desktop.

https://tangrams.readthedocs.io/en/latest/API-Reference/Javascript-API/#screenshot-background-white

We should add these parameters to the filename (because 126 files called `screenshot.png` in your downloads folder is no fun): 

- spaceID (token?)
- basemap value
- any query parameters that are not default -- points, lines, buildings, roads
- color value (range, rank, xray, etc)
- palette value, and flip if true
- z/x/y
- tag (unescaped)

ZH3etXkX_refill-dark&colors=range&points=3&tags=hour@03&property=index&palette=red-purple-blue&paletteFlip=true#13.463743248899014_40.7430_-73.9821.png

**Comment by bcamper** [comment]
Completed in #20.
