### ISSUE TITLE
mobile-optimized view

### ISSUE THREAD

**Issue by burritojustice** [burritojustice/xyz_space_invader#22]
fewer divs. maybe just properties?

**Comment by burritojustice** [comment]
maybe we just detect width, and if it's under a certain limit, we hide the tag panes on the right side, and if the orientation is portrait, we hide everything? 

https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by burritojustice** [comment]
or we integrate this into a "demo mode" that would be good to send a configured map to people who don't know the tool yet -- a single pane that has title info, count/size, the property being filtered, the histogram and colors...

**Comment by bcamper** [comment]
done!
