### ISSUE TITLE
range -> sort by values, rank -> sort by count

### ISSUE THREAD

**Issue by burritojustice** [burritojustice/xyz_space_invader#25]
If `range` is selected, automatically sort the list by values.

If `rank` is selected, automatically sort the list by count.

This way, the colors will be 'in order' regardless of the mode selected.

**Comment by bcamper** [comment]
Done in 95a6127b3dd5004dfac28ef00bb55af798465c04 and d4905c91973ec7ef706a8a09755080a781a83cee.
