### ISSUE TITLE
catch the r in command-r when reloading so roads don't get hidden

### ISSUE THREAD

**Issue by burritojustice** [burritojustice/xyz_space_invader#29]
Also, using command-c to copy a value in the preference pane toggles the color keyboard mode. Do we want to deprecate `c`at this point since we have a menu?

**Comment by bcamper** [comment]
There actually isn't a straightforward or airtight way to do this. You can't check active key state in the browser, you actually need to track *all* key up and down events and store that state continuously (but even then, sometimes events slip through in my experience).

We're better off not using keys that have side effects like this :)

Generally, I also suggest changing these to a checkbox or dropdown depending on option values.

**Comment by burritojustice** [comment]
changed roads to `-v` for the time being
