### ISSUE TITLE
checkbox to hide outliers

### ISSUE THREAD

**Issue by burritojustice** [burritojustice/xyz_space_invader#31]
Add a checkbox to hide features with values outside of the selected min/max values.

This would add a filter to the `_xyz_points`, ``_xyz_lines`, and _xyz_polygons` draw groups, like this:

`scene.config.layers._xyz_dots.filter = {'mag': { 'min': 5},{'max': 9}}`

and then `scene.updateConfig()`

Since all the outliers are already getting the same colors, this means we don't need to adjust the color range!

**Comment by bcamper** [comment]
Done in 05e892de357280fc2f0b42386db8ec1b2aa5be71 b3c2340a26dd2525d56cf2cdb89117a93f7949a3
