### ISSUE TITLE
toggle tags -- global vs viewport

### ISSUE THREAD

**Issue by burritojustice** [burritojustice/xyz_space_invader#4]
XYZ Space Invader aggregates all tags seen as the user interacts with the map. This is good for smaller datasets, but can get awkward with larger ones (like the Microsoft buildings) where a global view of tags is less useful.

In the tags panel, we should add a "show viewport tags / show global tags" button.

For the global list, we should also read the list of the top 50 tags from the `/statistics` endpoint.

**Comment by burritojustice** [comment]
global/viewport logic looking good. should be straightforward to import the tags from `/statistics` into the global tag list.

https://xyz.api.here.com/hub/static/swagger/#/Read_Features/getStatistics

**Comment by bcamper** [comment]
Global ("all seen") vs. local ("viewport-ish") previously added. Now seeing with top tags from stats endpoint with https://github.com/burritojustice/xyz_space_invader/commit/73255804f3d07616fc5bf8f5744108c552dfa767.
