### ISSUE TITLE
filter features client side by clicking on color property panel

### ISSUE THREAD

**Issue by burritojustice** [burritojustice/xyz_space_invader#8]
Filtering server side by tags is great, but it would also be nice to be able to filter client side.

Maybe we could click on the colored circle or value of the property to isolate it (though this raises the question of how to select multiple things).

![image](https://user-images.githubusercontent.com/3979711/57481753-afe12580-7257-11e9-8c15-ba673c66ee14.png)

So in the image above, clicking on the blue circle and/or `Twitter` would cause only those features to appear on the map, but the full list of property values would still be listed but with some indication that they are disabled.

🔴 ~Mobile~
🎾 ~Phone~
🌕 ~Web~
🔵 Twitter

**Comment by bcamper** [comment]
This was added recently.
